src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $serv_nom = null;

    #[ORM\Column(length: 20)]
    private ?string $serv_telephone = null;

    #[ORM\Column(length: 50)]
    #[Assert\Email(['message' => '"{{ value }}" : adresse email invalide.'])]
    private ?string $serv_mail = null;

    #[ORM\OneToMany(mappedBy: 'fourni_service', targetEntity: Fournisseur::class)]
    private Collection $fournisseurs;

    #[ORM\OneToMany(mappedBy: 'com_service', targetEntity: Commercial::class)]
    private Collection $serv_commercials;

    public function __construct()
    {
        $this->fournisseurs = new ArrayCollection();
        $this->serv_commercials = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getServNom(): ?string
    {
        return $this->serv_nom;
    }

    public function setServNom(string $serv_nom): self
    {
        $this->serv_nom = $serv_nom;

        return $this;
    }

    public function getServTelephone(): ?string
    {
        return $this->serv_telephone;
    }

    public function setServTelephone(string $serv_telephone): self
    {
        $this->serv_telephone = $serv_telephone;

        return $this;
    }

    public function getServMail(): ?string
    {
        return $this->serv_mail;
    }

    public function setServMail(string $serv_mail): self
    {
        $this->serv_mail = $serv_mail;

        return $this;
    }

    /**
     * @return Collection<int, Fournisseur>
     */
    public function getFournisseurs(): Collection
    {
        return $this->fournisseurs;
    }

    public function addFournisseur(Fournisseur $fournisseur): self
    {
        if (!$this->fournisseurs->contains($fournisseur)) {
            $this->fournisseurs->add($fournisseur);
            $fournisseur->setFourniService($this);
        }

        return $this;
    }

    public function removeFournisseur(Fournisseur $fournisseur): self
    {
        if ($this->fournisseurs->removeElement($fournisseur)) {
            // set the owning side to null (unless already changed)
            if ($fournisseur->getFourniService() === $this) {
                $fournisseur->setFourniService(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commercial>
     */
    public function getServCommercials(): Collection
    {
        return $this->serv_commercials;
    }

    public function addServCommercial(Commercial $servCommercial): self
    {
        if (!$this->serv_commercials->contains($servCommercial)) {
            $this->serv_commercials->add($servCommercial);
            $servCommercial->setComService($this);
        }

        return $this;
    }

    public function removeServCommercial(Commercial $servCommercial): self
    {
        if ($this->serv_commercials->removeElement($servCommercial)) {
            // set the owning side to null (unless already changed)
            if ($servCommercial->getComService() === $this) {
                $servCommercial->setComService(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->serv_nom;
    }

}

src/Form/ServiceType.php
<?php

namespace App\Form;

use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('serv_nom')
            ->add('serv_telephone')
            ->add('serv_mail')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Form\ServiceType;
use App\Repository\ServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/service')]
class ServiceController extends AbstractController
{
    #[Route('/', name: 'app_service_index', methods: ['GET'])]
    public function index(ServiceRepository $serviceRepository): Response
    {
        return $this->render('service/index.html.twig', [
            'services' => $serviceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_service_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ServiceRepository $serviceRepository): Response
    {
        $service = new Service();
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->add($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_show', methods: ['GET'])]
    public function show(Service $service): Response
    {
        return $this->render('service/show.html.twig', [
            'service' => $service,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_service_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->add($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_delete', methods: ['POST'])]
    public function delete(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->request->get('_token'))) {
            $serviceRepository->remove($service, true);
        }

        return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/service/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Service{% endblock %}

{% block body %}
    <h1>Edit Service</h1>

    {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_service_index') }}">back to list</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}

templates/service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service index{% endblock %}

{% block body %}
    <h1>Service index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Serv_nom</th>
                <th>Serv_telephone</th>
                <th>Serv_mail</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for service in services %}
            <tr>
                <td>{{ service.id }}</td>
                <td>{{ service.servNom }}</td>
                <td>{{ service.servTelephone }}</td>
                <td>{{ service.servMail }}</td>
                <td>
                    <a href="{{ path('app_service_show', {'id': service.id}) }}">show</a>
                    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_service_new') }}">Create new</a>
{% endblock %}

templates/service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Service{% endblock %}

{% block body %}
    <h1>Create new Service</h1>

    {{ include('service/_form.html.twig') }}

    <a href="{{ path('app_service_index') }}">back to list</a>
{% endblock %}

templates/service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service{% endblock %}

{% block body %}
    <h1>Service</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ service.id }}</td>
            </tr>
            <tr>
                <th>Serv_nom</th>
                <td>{{ service.servNom }}</td>
            </tr>
            <tr>
                <th>Serv_telephone</th>
                <td>{{ service.servTelephone }}</td>
            </tr>
            <tr>
                <th>Serv_mail</th>
                <td>{{ service.servMail }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_service_index') }}">back to list</a>

    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}