src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Length(max:50)]
    private ?string $prod_marque = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min:1, max:50)]
    private ?string $prod_modele = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min:1, max:50)]
    private ?string $prod_finition = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max:255)]
    private ?string $prod_lib_court = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $prod_lib_long = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    #[Assert\NotNull()]
    #[Assert\PositiveOrZero()]
    private ?string $prod_prix = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max:255)]
    private ?string $prod_photo = null;

    #[ORM\Column]
    private ?bool $prod_actif = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min:1, max:50)]
    private ?string $prod_reference = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Rubrique $prod_rubrique = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Fournisseur $prod_fournisseur = null;

    #[ORM\Column]
    private ?int $prod_stock = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProdMarque(): ?string
    {
        return $this->prod_marque;
    }

    public function setProdMarque(?string $prod_marque): self
    {
        $this->prod_marque = $prod_marque;

        return $this;
    }

    public function getProdModele(): ?string
    {
        return $this->prod_modele;
    }

    public function setProdModele(string $prod_modele): self
    {
        $this->prod_modele = $prod_modele;

        return $this;
    }

    public function getProdFinition(): ?string
    {
        return $this->prod_finition;
    }

    public function setProdFinition(string $prod_finition): self
    {
        $this->prod_finition = $prod_finition;

        return $this;
    }

    public function getProdLibCourt(): ?string
    {
        return $this->prod_lib_court;
    }

    public function setProdLibCourt(?string $prod_lib_court): self
    {
        $this->prod_lib_court = $prod_lib_court;

        return $this;
    }

    public function getProdLibLong(): ?string
    {
        return $this->prod_lib_long;
    }

    public function setProdLibLong(?string $prod_lib_long): self
    {
        $this->prod_lib_long = $prod_lib_long;

        return $this;
    }

    public function getProdPrix(): ?string
    {
        return $this->prod_prix;
    }

    public function setProdPrix(string $prod_prix): self
    {
        $this->prod_prix = $prod_prix;

        return $this;
    }

    public function getProdPhoto(): ?string
    {
        return $this->prod_photo;
    }

    public function setProdPhoto(?string $prod_photo): self
    {
        $this->prod_photo = $prod_photo;

        return $this;
    }

    public function isProdActif(): ?bool
    {
        return $this->prod_actif;
    }

    public function setProdActif(bool $prod_actif): self
    {
        $this->prod_actif = $prod_actif;

        return $this;
    }

    public function getProdReference(): ?string
    {
        return $this->prod_reference;
    }

    public function setProdReference(string $prod_reference): self
    {
        $this->prod_reference = $prod_reference;

        return $this;
    }

    public function getProdRubrique(): ?Rubrique
    {
        return $this->prod_rubrique;
    }

    public function setProdRubrique(?Rubrique $prod_rubrique): self
    {
        $this->prod_rubrique = $prod_rubrique;

        return $this;
    }

    public function getProdFournisseur(): ?Fournisseur
    {
        return $this->prod_fournisseur;
    }

    public function setProdFournisseur(?Fournisseur $prod_fournisseur): self
    {
        $this->prod_fournisseur = $prod_fournisseur;

        return $this;
    }

    public function getProdStock(): ?int
    {
        return $this->prod_stock;
    }

    public function setProdStock(int $prod_stock): self
    {
        $this->prod_stock = $prod_stock;

        return $this;
    }

    public function __toString()
    {
        return $this->prod_modele;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prod_marque')
            ->add('prod_modele')
            ->add('prod_finition')
            ->add('prod_lib_court')
            ->add('prod_lib_long')
            ->add('prod_prix')
            ->add('prod_photo')
            ->add('prod_actif')
            ->add('prod_reference')
            ->add('prod_rubrique')
            ->add('prod_fournisseur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProduitRepository $produitRepository): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $produitRepository->add($produit, true);

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form ,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $produitRepository->add($produit, true);

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $produitRepository->remove($produit, true);
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet article?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button type="btn" class="btn btn-warning bg-gradient btn-sm">Suppression</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button type="btn" class="btn btn-success bg-gradient btn-sm">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Édition Produit
{% endblock %}

{% block body %}
  <h3>Édition Produit</h3>

  {{ include('produit/_form.html.twig', { button_label: 'Mise à jour' }) }}

  <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_index') }}">Retour</a>

  {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Produit index
{% endblock %}

{% block body %}
  <div class="cargo">
    <h3>Produit index</h3>

    <table class="table">
      <thead>
        <tr>
          <th>Prod_marque</th>
          <th>Prod_modele</th>
          <th>Prod_finition</th>
          <th>Prod_lib_court</th>
          <th>Prod_lib_long</th>
          <th>Prod_prix</th>
          <th>Prod_photo</th>
          <th>Prod_actif</th>
          <th>Prod_reference</th>
          <th>actions</th>
        </tr>
      </thead>
      <tbody>
        {% for produit in produits %}
          <tr>
            <td>{{ produit.prodMarque }}</td>
            <td>{{ produit.prodModele }}</td>
            <td>{{ produit.prodFinition }}</td>
            <td>{{ produit.prodLibCourt }}</td>
            <td>{{ produit.prodLibLong }}</td>
            <td>{{ produit.prodPrix }}</td>
            <td>{{ produit.prodPhoto }}</td>
            <td>{{ produit.prodActif ? 'Oui' : 'Non' }}</td>
            <td>{{ produit.prodReference }}</td>
            <td>
              <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_show', { id: produit.id }) }}">Détail</a>
              <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_edit', { id: produit.id }) }}">Éditer</a>
            </td>
          </tr>
        {% else %}
          <tr>
            <td colspan="11">Aucun produit en base</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_new') }}">Nouvel article</a>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Produit{% endblock %}

{% block body %}
    <h3>Création d'un Produit</h3>

    {{ include('produit/_form.html.twig') }}

    <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_index') }}">Retour</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Produit
{% endblock %}

{% block body %}
  <div class="cargo">
    <h3>Produit</h3>

    <ul class="fiche_obj">
      <li>
        <table class="table">
          <tbody>
            <tr>
              <th>Id</th>
              <td>{{ produit.id }}</td>
            </tr>
            <tr>
              <th>Prod_marque</th>
              <td>{{ produit.prodMarque }}</td>
            </tr>
            <tr>
              <th>Prod_modele</th>
              <td>{{ produit.prodModele }}</td>
            </tr>
            <tr>
              <th>Prod_finition</th>
              <td>{{ produit.prodFinition }}</td>
            </tr>
            <tr>
              <th>Prod_lib_court</th>
              <td>{{ produit.prodLibCourt }}</td>
            </tr>
            <tr>
              <th>Prod_lib_long</th>
              <td>{{ produit.prodLibLong }}</td>
            </tr>
            <tr>
              <th>Prod_prix</th>
              <td>{{ produit.prodPrix }}</td>
            </tr>
            <tr>
              <th>Prod_photo</th>
              <td>{{ produit.prodPhoto }}</td>
            </tr>
            <tr>
              <th>Prod_actif</th>
              <td>{{ produit.prodActif ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
              <th>Prod_reference</th>
              <td>{{ produit.prodReference }}</td>
            </tr>
          </tbody>
        </table>
      </li>
      <li>
        <div class="photo-catalogue">
          <img src="/asset/media/catalogue/{{ produit.prodPhoto }}" alt="{{ produit.prodPhoto }}" />
        </div>
      </li>
    </ul>

    <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_index') }}">Retour</a>

    <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_produit_edit', { id: produit.id }) }}">Édition</a>

    {{ include('produit/_delete_form.html.twig') }}
  </div>
{% endblock %}