src/Entity/Fournisseur.php
<?php

namespace App\Entity;

use App\Repository\FournisseurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FournisseurRepository::class)]
class Fournisseur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $fourni_societe = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fourni_nom = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fourni_prenom = null;

    #[ORM\Column(length: 20)]
    private ?string $fourni_telephone = null;

    #[ORM\Column(length: 50)]
    #[Assert\Email(['message' => '"{{ value }}" : adresse email invalide.'])]
    private ?string $fourni_mail = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fourni_adresse = null;

    #[ORM\Column(length: 16, nullable: true)]
    private ?string $fourni_cp = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fourni_ville = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fourni_region = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fourni_pays = null;

    #[ORM\Column]
    private ?bool $fourni_constructeur = null;

    #[ORM\Column]
    private ?bool $fourni_importateur = null;

    #[ORM\OneToMany(mappedBy: 'prod_fournisseur', targetEntity: Produit::class)]
    private Collection $produits;

    #[ORM\ManyToOne(inversedBy: 'fournisseurs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Service $fourni_service = null;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFourniSociete(): ?string
    {
        return $this->fourni_societe;
    }

    public function setFourniSociete(string $fourni_societe): self
    {
        $this->fourni_societe = $fourni_societe;

        return $this;
    }

    public function getFourniNom(): ?string
    {
        return $this->fourni_nom;
    }

    public function setFourniNom(?string $fourni_nom): self
    {
        $this->fourni_nom = $fourni_nom;

        return $this;
    }

    public function getFourniPrenom(): ?string
    {
        return $this->fourni_prenom;
    }

    public function setFourniPrenom(?string $fourni_prenom): self
    {
        $this->fourni_prenom = $fourni_prenom;

        return $this;
    }

    public function getFourniTelephone(): ?string
    {
        return $this->fourni_telephone;
    }

    public function setFourniTelephone(string $fourni_telephone): self
    {
        $this->fourni_telephone = $fourni_telephone;

        return $this;
    }

    public function getFourniMail(): ?string
    {
        return $this->fourni_mail;
    }

    public function setFourniMail(string $fourni_mail): self
    {
        $this->fourni_mail = $fourni_mail;

        return $this;
    }

    public function getFourniAdresse(): ?string
    {
        return $this->fourni_adresse;
    }

    public function setFourniAdresse(?string $fourni_adresse): self
    {
        $this->fourni_adresse = $fourni_adresse;

        return $this;
    }

    public function getFourniCp(): ?string
    {
        return $this->fourni_cp;
    }

    public function setFourniCp(?string $fourni_cp): self
    {
        $this->fourni_cp = $fourni_cp;

        return $this;
    }

    public function getFourniVille(): ?string
    {
        return $this->fourni_ville;
    }

    public function setFourniVille(?string $fourni_ville): self
    {
        $this->fourni_ville = $fourni_ville;

        return $this;
    }

    public function getFourniRegion(): ?string
    {
        return $this->fourni_region;
    }

    public function setFourniRegion(?string $fourni_region): self
    {
        $this->fourni_region = $fourni_region;

        return $this;
    }

    public function getFourniPays(): ?string
    {
        return $this->fourni_pays;
    }

    public function setFourniPays(?string $fourni_pays): self
    {
        $this->fourni_pays = $fourni_pays;

        return $this;
    }

    public function isFourniConstructeur(): ?bool
    {
        return $this->fourni_constructeur;
    }

    public function setFourniConstructeur(bool $fourni_constructeur): self
    {
        $this->fourni_constructeur = $fourni_constructeur;

        return $this;
    }

    public function isFourniImportateur(): ?bool
    {
        return $this->fourni_importateur;
    }

    public function setFourniImportateur(bool $fourni_importateur): self
    {
        $this->fourni_importateur = $fourni_importateur;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setProdFournisseur($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getProdFournisseur() === $this) {
                $produit->setProdFournisseur(null);
            }
        }

        return $this;
    }

    public function getFourniService(): ?Service
    {
        return $this->fourni_service;
    }

    public function setFourniService(?Service $fourni_service): self
    {
        $this->fourni_service = $fourni_service;

        return $this;
    }

    public function __toString()
    {
        return $this->fourni_societe;
    }

}

src/Form/FournisseurType.php
<?php

namespace App\Form;

use App\Entity\Fournisseur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FournisseurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fourni_societe')
            ->add('fourni_nom')
            ->add('fourni_prenom')
            ->add('fourni_telephone')
            ->add('fourni_mail')
            ->add('fourni_adresse')
            ->add('fourni_cp')
            ->add('fourni_ville')
            ->add('fourni_region')
            ->add('fourni_pays')
            ->add('fourni_constructeur')
            ->add('fourni_importateur')
            ->add('fourni_service')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fournisseur::class,
        ]);
    }
}

src/Controller/FournisseurController.php
<?php

namespace App\Controller;

use App\Entity\Fournisseur;
use App\Form\FournisseurType;
use App\Repository\FournisseurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/fournisseur')]
class FournisseurController extends AbstractController
{
    #[Route('/', name: 'app_fournisseur_index', methods: ['GET'])]
    public function index(FournisseurRepository $fournisseurRepository): Response
    {
        return $this->render('fournisseur/index.html.twig', [
            'fournisseurs' => $fournisseurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_fournisseur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FournisseurRepository $fournisseurRepository): Response
    {
        $fournisseur = new Fournisseur();
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fournisseurRepository->add($fournisseur, true);

            return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fournisseur/new.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fournisseur_show', methods: ['GET'])]
    public function show(Fournisseur $fournisseur): Response
    {
        return $this->render('fournisseur/show.html.twig', [
            'fournisseur' => $fournisseur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fournisseur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Fournisseur $fournisseur, FournisseurRepository $fournisseurRepository): Response
    {
        $form = $this->createForm(FournisseurType::class, $fournisseur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fournisseurRepository->add($fournisseur, true);

            return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('fournisseur/edit.html.twig', [
            'fournisseur' => $fournisseur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fournisseur_delete', methods: ['POST'])]
    public function delete(Request $request, Fournisseur $fournisseur, FournisseurRepository $fournisseurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fournisseur->getId(), $request->request->get('_token'))) {
            $fournisseurRepository->remove($fournisseur, true);
        }

        return $this->redirectToRoute('app_fournisseur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/fournisseur/_delete_form.html.twig
<form method="post" action="{{ path('app_fournisseur_delete', {'id': fournisseur.id}) }}" onsubmit="return confirm('Voulez-vous supprimer ce fournisseur?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fournisseur.id) }}">
    <button type="btn" class="btn btn-warning bg-gradient btn-sm">Suppression</button>
</form>

templates/fournisseur/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button type="btn" class="btn btn-success bg-gradient btn-sm">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/fournisseur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Édition Fournisseur
{% endblock %}

{% block body %}
  <h3>Édition Fournisseur</h3>

  {{ include('fournisseur/_form.html.twig', { button_label: 'Mise à jour' }) }}

  <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_index') }}">Retour</a>

  {{ include('fournisseur/_delete_form.html.twig') }}
{% endblock %}

templates/fournisseur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Fournisseur index
{% endblock %}

{% block body %}
  <div class="cargo">
    <h3>Fournisseur index</h3>

    <table class="table">
      <thead>
        <tr>
          <th>Fourni_societe</th>
          <th>Fourni_nom</th>
          <th>Fourni_prenom</th>
          <th>Fourni_telephone</th>
          <th>Fourni_mail</th>
          <th>Fourni_adresse</th>
          <th>Fourni_cp</th>
          <th>Fourni_ville</th>
          <th>Fourni_region</th>
          <th>Fourni_pays</th>
          <th>Fourni_constructeur</th>
          <th>Fourni_importateur</th>
          <th>actions</th>
        </tr>
      </thead>
      <tbody>
        {% for fournisseur in fournisseurs %}
          <tr>
            <td>{{ fournisseur.fourniSociete }}</td>
            <td>{{ fournisseur.fourniNom }}</td>
            <td>{{ fournisseur.fourniPrenom }}</td>
            <td>{{ fournisseur.fourniTelephone }}</td>
            <td>{{ fournisseur.fourniMail }}</td>
            <td>{{ fournisseur.fourniAdresse }}</td>
            <td>{{ fournisseur.fourniCp }}</td>
            <td>{{ fournisseur.fourniVille }}</td>
            <td>{{ fournisseur.fourniRegion }}</td>
            <td>{{ fournisseur.fourniPays }}</td>
            <td>{{ fournisseur.fourniConstructeur ? 'Yes' : 'No' }}</td>
            <td>{{ fournisseur.fourniImportateur ? 'Yes' : 'No' }}</td>
            <td>
              <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_show', { id: fournisseur.id }) }}">Détail</a>
              <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_edit', { id: fournisseur.id }) }}">Éditer</a>
            </td>
          </tr>
        {% else %}
          <tr>
            <td colspan="14">no records found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_new') }}">Nouveau Fournisseur</a>
{% endblock %}

templates/fournisseur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Fournisseur{% endblock %}

{% block body %}
    <h3>Création d'un Fournisseur</h3>

    {{ include('fournisseur/_form.html.twig') }}

    <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_index') }}">Retour</a>
{% endblock %}

templates/fournisseur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Fournisseur
{% endblock %}

{% block body %}
  <div class="cargo">
    <h3>Fournisseur</h3>

    <ul class="fiche_obj">
      <table class="table">
        <tbody>
          <tr>
            <th>Id</th>
            <td>{{ fournisseur.id }}</td>
          </tr>
          <tr>
            <th>Fourni_societe</th>
            <td>{{ fournisseur.fourniSociete }}</td>
          </tr>
          <tr>
            <th>Fourni_nom</th>
            <td>{{ fournisseur.fourniNom }}</td>
          </tr>
          <tr>
            <th>Fourni_prenom</th>
            <td>{{ fournisseur.fourniPrenom }}</td>
          </tr>
          <tr>
            <th>Fourni_telephone</th>
            <td>{{ fournisseur.fourniTelephone }}</td>
          </tr>
          <tr>
            <th>Fourni_mail</th>
            <td>{{ fournisseur.fourniMail }}</td>
          </tr>
          <tr>
            <th>Fourni_adresse</th>
            <td>{{ fournisseur.fourniAdresse }}</td>
          </tr>
          <tr>
            <th>Fourni_cp</th>
            <td>{{ fournisseur.fourniCp }}</td>
          </tr>
          <tr>
            <th>Fourni_ville</th>
            <td>{{ fournisseur.fourniVille }}</td>
          </tr>
          <tr>
            <th>Fourni_region</th>
            <td>{{ fournisseur.fourniRegion }}</td>
          </tr>
          <tr>
            <th>Fourni_pays</th>
            <td>{{ fournisseur.fourniPays }}</td>
          </tr>
          <tr>
            <th>Fourni_constructeur</th>
            <td>{{ fournisseur.fourniConstructeur ? 'Yes' : 'No' }}</td>
          </tr>
          <tr>
            <th>Fourni_importateur</th>
            <td>{{ fournisseur.fourniImportateur ? 'Yes' : 'No' }}</td>
          </tr>
        </tbody>
      </table>
    </ul>

    <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_index') }}">Retour</a>

    <a class="btn btn-success bg-gradient btn-sm" href="{{ path('app_fournisseur_edit', { id: fournisseur.id }) }}">Édition</a>

    {{ include('fournisseur/_delete_form.html.twig') }}
  </div>
{% endblock %}